### ISSUE TITLE
EuroSAT number of images

### ISSUE THREAD

**Issue by wangyi111** [ServiceNow/geo-bench#10]
Hi! Thanks for the nice benchmark. I noticed that in the paper table1 "m-eurosat" has 16200/996/996 train/val/test images, while what we got from geobench-download (the [published data in huggingface](https://huggingface.co/datasets/recursix/geo-bench-1.0/blob/main/classification_v1.0/m-eurosat.zip)) has only 2000/1000/1000 images. The results reported in the paper seem to be based on the full version. Is this an uploading mistake or did I miss anything?

**Comment by recursix** [comment]
Apologies for the delay. The openreview has the latest classification results. The arxiv will be updated very soon, we were waiting for the last segmentation experiment to re-run on GEO-Bench 1.0.
