### ISSUE TITLE
ModuleNotFoundError: No module named 'ccb' while accessing h5py files

### ISSUE THREAD

**Issue by nikita-0209** [ServiceNow/geo-bench#14]
I have been trying to access h5py (specifically of the chesapeake dataset) using a version of [load_sample_hdf5](https://github.com/ServiceNow/geo-bench/blob/main/geobench/dataset.py#L873) in my local script, but it runs into an error. 

Remark: I am not using the geobench toolkit, I downloaded the dataset from the linked Zenodo, and was working with that. 

Please let me know if I should provide any additional information. 

```
Traceback (most recent call last)
<ipython-input-7-670131b9a5ea> in <cell line: 1>()
      1 with h5py.File( "/content/drive/My Drive/id_002192.hdf5", "r") as fp:
----> 2         attr_dict = pickle.loads(ast.literal_eval(fp.attrs["pickle"]))
      3         band_names = attr_dict.get("bands_order", fp.keys())

ModuleNotFoundError: No module named 'ccb'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
```

**Comment by recursix** [comment]
Thank you for reporting.

The dataset from Zenodo are deprecated. 
Make sure to install the latest version and download the dataset using the downloader as described in the readme.
