### ISSUE TITLE
Missing related work

### ISSUE THREAD

**Issue by simidjievskin** [ServiceNow/geo-bench#5]
Hi,

very interesting work! It seems you've missed a related work tackling related challenges:
AiTLAS Benchmark Arena 
github: https://github.com/biasvariancelabs/aitlas-arena
paper: "Current trends in deep learning for Earth Observation: An open-source benchmark arena for image classification" https://www.sciencedirect.com/science/article/pii/S0924271623000205

cheers,

**Comment by recursix** [comment]
Ohh wow, thanks for the reference. We'll add it to the camera-ready paper.

**Comment by recursix** [comment]
Added to the camera ready. Should appear shortly.
