### ISSUE TITLE
tqdm-contrib dependancies

### ISSUE THREAD

**Issue by darkblue-b** [ServiceNow/geo-bench#7]
hello team from Berkeley -- good work and very interested to see this.  The python3 `tqdm` packaged for GNU-Debian-Ubuntu 22.04 LTS (jammy) does not have a contrib section? With a quick look using standard packaged python3, I saw no way to satisfy the the `tqdm.contrib.concurrent thread_map` feature extra dependency. In my test for data download I got enough bandwidth with a single stream.  ( ~18MB/sec at OSUOSL)

**Comment by recursix** [comment]
Thanks for reporting. 

Let me try to understand better.
Installing `geo-benchmark` has dependencies already satisfied for `tqdm` and it's from your ubuntu tqdm package?

does `pip install tqdm' solve the problem?

**Comment by darkblue-b** [comment]
some context :  installing python .. on GNU-Debian-Linux, there are python3 packages in dot-deb format. Most of those packages are very closely in sync with modern updates, especially `numpy` `pandas` and other popular data-science. So it is desirable to stay close to these standard installs for maximum portability.  It is true that there is no way that Debian or Ubuntu python packages can be "cutting edge" it is too much work for the packagers. Contrast to the benefits of python dot-deb.. integration into a binary ecosystem with many tens of thousands of applications available, tested and compatible. For the security-minded, signed packages from a known source are valuable or even required.

You as project implementer choose your own contents, to meet your own goals -- 100% agree --  "do-ocracy" speaks.  And, when you make choices for your package dependencies, you can consider the compatibility and portability of the library.

I am telling you today that on a popular and stable Linux OS, the `tqdm.contrib.concurrent` is not available, including `thread_map`  on the LTS version 22.04.  Maybe I missed it ?

**Comment by recursix** [comment]
we're considering moving the dataset to hugging face so this would mostly solve the problem once we change to a new download script. 

I mainly need to know. Is there a quick workaround for your situation? I.e. if you do a manual `pip install geo-benchmark`

**Comment by darkblue-b** [comment]
my situation is -- I am senior editor for a Linux distribution on maps, mapping and spatial data;  the purpose of the exercise is to use FAIR and Reproducible Science principles to recreate the results you will show with GEO-Bench -- not on the cloud, not on HuggingFace, but reproduce with authentic inputs.

It took me ten minutes total to remove the global environment variable, remove the `tqdm thread_map` and revert to a single-queue, which I did.

In my case, I ran on a VM in the Oregon State University Open Source Lab (OSUOSL) getting about 18MB/sec download speed for the data.  That worked fine with single stream I/O.

**Comment by darkblue-b** [comment]
better ref  'Toward Foundation Models for Earth Monitoring: Proposal for a Climate Change Benchmark' dec2021  3.1 Benchmark -

**Comment by recursix** [comment]
> better ref 'Toward Foundation Models for Earth Monitoring: Proposal for a Climate Change Benchmark' dec2021 3.1 Benchmark -

This is us too. We'll reference it in the camera ready of the paper.

**Comment by recursix** [comment]
>  #from geobench import config

I don't understand why config.GEO_BENCH_DIR is an issue

> not on the cloud, not on HuggingFace

The benchmark data will likely be hosted on huggingface soon. The download script will download from there instead of Zenodo so it will solve the problems. You won't have to "run in the cloud".

>  getting about 18MB/sec download speed for the data

zenodo is not consistent on download speed. We frequently are throttled at ~300k. the parallel download is a workaround to get a ~10x speedup.

> `from tqdm import tqdm
#from tqdm.contrib.concurrent import thread_map`

I'll switch to single thread. This will solve the problem (with occasional slow download speed until we move to hugginface)
